
export const SECTIONS_FETCHED = 'SECTIONS_FETCHED';
export const SECTION_SELECTED = 'SECTION_SELECTED';
export const OPEN_GH  = "OPEN_GITHUB_REPOSITORIES";
export const OPEN_SOF = "OPEN_STACKOVERFLOW_POSTS";

